import{OPERATORS,hkClock,serviceStatus,variants,stopsFor,emptyRow,onboardValues,nearestStops,makeCSV}from'./core.js';import{load,save,loadSurveyor,saveSurveyor}from'./storage.js';import{routes}from'./data.js';
const $=id=>document.getElementById(id);let state=load(),data,matches=[],map,markers=[],position,watch;const cur=()=>state.surveys.find(x=>x.id===state.currentId);const error=x=>{$('error').textContent=x;$('error').hidden=!x};
function persist(){try{save(state);$('saveStatus').textContent='Saved on this browser'}catch{$('saveStatus').textContent='NOT SAVED';error('Browser storage is unavailable. Download a CSV before closing.')}}
function edit(){const s=cur();if(s)s.updatedAt=new Date().toISOString();persist()}
function list(){ $('saved').replaceChildren(new Option('New survey',''));for(const s of[...state.surveys].reverse())$('saved').add(new Option(`${s.date} · ${s.route.route} ${OPERATORS[s.route.operator]} → ${s.route.dest.en} · ${s.vehicle||'No vehicle'}`,s.id));$('saved').value=state.currentId||'' }
async function search(force=false){const number=$('route').value.trim();if(!number)return;try{data=await routes(x=>$('dataStatus').textContent=x,force);matches=variants(data,number,$('operator').value);state.search={number,operator:$('operator').value,upcoming:$('upcoming').value};persist();renderMatches()}catch(e){error(e.message)}}
function renderMatches(){const c=hkClock();$('clock').textContent=`Service filter: ${c.date} ${c.time} (Hong Kong)`;$('results').replaceChildren();$('otherResults').replaceChildren();let hidden=0;for(const r of matches){const s=serviceStatus(r,data,new Date(),+$('upcoming').value),b=document.createElement('button');b.className='route';b.textContent=`${OPERATORS[r.operator]} ${r.route} · ${r.orig.en} → ${r.dest.en}`;const a=document.createElement('span');a.textContent=`${r.orig.zh||''} → ${r.dest.zh||''} · ${r.direction} · Variant ${r.serviceType} · ${r.stopIds.length} stops`;const badge=document.createElement('span');badge.className=s.kind;badge.textContent=s.text;b.append(a,badge);b.onclick=()=>selectRoute(r);if(s.kind==='inactive'){$('otherResults').append(b);hidden++}else $('results').append(b)}$('other').hidden=!hidden;$('otherTitle').textContent=`Show ${hidden} other directions / route variants`;if(!$('results').children.length)$('results').textContent=matches.length?'No scheduled variants in this window. Expand the other variants.':'No matching routes found.'}
function selectRoute(route){const stops=stopsFor(route,data),s={id:crypto.randomUUID(),route,stops,rows:stops.map(emptyRow),date:hkClock().date,vehicle:'',notes:'',surveyor:$('surveyor').value,startIndex:null,pendingStart:null,startSource:null,activeIndex:0,updatedAt:new Date().toISOString()};state.surveys.push(s);state.currentId=s.id;persist();renderSurvey()}
function renderSurvey(){const s=cur();list();$('survey').hidden=!s;if(!s)return;$('surveyor').value=s.surveyor;$('selected').textContent=`${OPERATORS[s.route.operator]} ${s.route.route} · ${s.route.orig.en} → ${s.route.dest.en} · Variant ${s.route.serviceType}`;$('date').value=s.date;$('vehicle').value=s.vehicle;$('notes').value=s.notes;$('start').replaceChildren(new Option('Choose or wait for GPS',''));$('active').replaceChildren();s.stops.forEach((x,i)=>{const label=`${i+1}. ${x.name.zh||''} · ${x.name.en||''}`;$('start').add(new Option(label,i));$('active').add(new Option(label,i))});$('start').value=s.pendingStart??'';$('body').replaceChildren();s.rows.forEach((r,i)=>{const tr=document.createElement('tr');tr.dataset.i=i;const name=document.createElement('td');name.textContent=`${i+1}. ${s.stops[i].name.zh||''} · ${s.stops[i].name.en||''}`;name.onclick=()=>active(i);tr.append(name);for(const f of['time','boarding','alighting','onboard','notes']){const td=document.createElement('td'),input=document.createElement('input');input.type=f==='time'?'time':f==='notes'?'text':'number';input.value=r[f];input.dataset.f=f;if(input.type==='number'){input.min=0;input.step=1}input.onfocus=()=>active(i,false);input.oninput=()=>{r[f]=input.value;if((f==='boarding'||f==='alighting')&&input.value!==''&&!r.time){r.time=hkClock().time;tr.querySelector('[data-f=time]').value=r.time}edit();counts()};td.append(input);if(f==='onboard')td.append(document.createElement('small'));tr.append(td)}$('body').append(tr)});setupMap();counts();active(s.activeIndex,false);startStatus();locate()}
function counts(){const s=cur(),v=onboardValues(s.rows);$('body').querySelectorAll('tr').forEach((tr,i)=>{const x=tr.querySelector('[data-f=onboard]'),derived=s.rows[i].onboard===''&&v[i]!=null;if(document.activeElement!==x)x.value=v[i]??'';x.classList.toggle('derived',derived);tr.querySelector('td:nth-child(5) small').textContent=derived?'auto':''})}
function active(i,center=true){const s=cur();if(!s||!s.stops[i])return;s.activeIndex=i;$('active').value=i;$('body').querySelectorAll('tr').forEach((r,n)=>r.classList.toggle('selectedRow',n===i));for(const[n,m]of markers.entries())m?.setIcon(icon(n,n===i));$('prev').disabled=$('entryPrev').disabled=i===0;$('next').disabled=$('entryNext').disabled=i===s.stops.length-1;if(center&&map)map.setView([s.stops[i].lat,s.stops[i].lng],18);persist()}
const icon=(i,selected)=>L.divIcon({html:i+1,className:`stopIcon${selected?' selected':''}`,iconSize:[28,28],iconAnchor:[14,14]});
function setupMap(){const s=cur();if(!window.L)return;if(!map){map=L.map('map').setView([22.32,114.17],18);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map)}markers.forEach(x=>x.remove());markers=s.stops.map((x,i)=>Number.isFinite(x.lat)?L.marker([x.lat,x.lng],{icon:icon(i,i===s.activeIndex)}).bindTooltip(`${i+1}. ${x.name.zh||''} · ${x.name.en||''}`,{permanent:true,direction:i%2?'left':'right'}).on('click',()=>active(i)).addTo(map):null);setTimeout(()=>map.invalidateSize(),0);map.setView([s.stops[s.activeIndex].lat,s.stops[s.activeIndex].lng],18)}
function locate(restart=false){if(!navigator.geolocation){$('gps').textContent='GPS unavailable; choose manually.';return}if(watch!==undefined&&!restart)return;if(watch!==undefined)navigator.geolocation.clearWatch(watch);watch=navigator.geolocation.watchPosition(p=>{position={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,timestamp:p.timestamp};if(map){if(!map.gps)map.gps=L.circleMarker([position.lat,position.lng],{radius:7,color:'#1670c5',fillOpacity:1}).addTo(map);else map.gps.setLatLng([position.lat,position.lng])}suggest()},e=>$('gps').textContent=e.code===1?'Location permission is off. Choose manually.':'Cannot get a fresh location.',{enableHighAccuracy:true,maximumAge:10000,timeout:20000})}
function suggest(){const s=cur();if(!s||!position)return;const n=nearestStops(s.stops,position)[0];if(!n)return;$('gps').textContent=`GPS ±${Math.round(position.accuracy)} m · Nearest: ${n.index+1}. ${n.name.en} (${Math.round(n.distance)} m away).`;if(s.startIndex==null&&s.startSource!=='manual'){s.pendingStart=n.index;s.startSource='gps';$('start').value=n.index;edit();startStatus()}}
function startStatus(){const s=cur();$('confirm').disabled=s.pendingStart==null;$('startStatus').textContent=s.startIndex==null?(s.pendingStart==null?'Choose a start stop, or allow GPS to suggest one.':`GPS suggestion / selection: ${s.pendingStart+1}. ${s.stops[s.pendingStart].name.en}. Confirm or change it.`):`Confirmed start: ${s.startIndex+1}. ${s.stops[s.startIndex].name.en}. Earlier stops remain available for backward calculation.`}
function download(){const s=cur(),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([makeCSV(s)],{type:'text/csv'}));a.download=`bus-${s.route.route}-${s.date}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000)}
$('surveyor').value=loadSurveyor();$('surveyor').oninput=()=>{saveSurveyor($('surveyor').value);if(cur()){cur().surveyor=$('surveyor').value;edit()}};$('search').onsubmit=e=>{e.preventDefault();search()};$('operator').onchange=()=>search();$('upcoming').onchange=()=>renderMatches();$('saved').onchange=()=>{state.currentId=$('saved').value||null;persist();renderSurvey()};$('new').onclick=()=>{state.currentId=null;persist();renderSurvey()};for(const[id,k]of[['date','date'],['vehicle','vehicle'],['notes','notes']])$(id).oninput=()=>{cur()[k]=$(id).value;edit();list()};$('start').onchange=()=>{const s=cur();s.pendingStart=$('start').value===''?null:+$('start').value;s.startSource='manual';edit();startStatus()};$('confirm').onclick=()=>{const s=cur();s.startIndex=s.pendingStart;edit();active(s.startIndex);startStatus()};$('active').onchange=()=>active(+$('active').value);for(const[id,d]of[['prev',-1],['entryPrev',-1],['next',1],['entryNext',1]])$(id).onclick=()=>active(cur().activeIndex+d);$('locate').onclick=()=>locate(true);$('myLocation').onclick=()=>position&&map.setView([position.lat,position.lng],18);$('selectedStop').onclick=()=>active(cur().activeIndex);$('whole').onclick=()=>map.fitBounds(cur().stops.filter(x=>Number.isFinite(x.lat)).map(x=>[x.lat,x.lng]),{padding:[20,20]});$('all').onchange=()=>document.body.classList.toggle('showAll',$('all').checked);$('csv').onclick=download;
const q=state.search||{};$('route').value=q.number||'';$('operator').value=q.operator||'';$('upcoming').value=q.upcoming||'30';renderSurvey();persist();if(q.number)search();window.addEventListener('pagehide',persist);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
