export const SUPABASE_URL='https://jirzkyvwfpbblvyivikw.supabase.co';
export const SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppcnpreXZ3ZnBiYmx2eWl2aWt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk1NDcwMDQsImV4cCI6MjA5NTEyMzAwNH0.rlaM5GKsC5WUtEXH_5VINFYDq4tCFdFiLo27s5B6-Xc';
